apiVersion: v1
kind: Service
metadata:
  name: aesthisa-svc
  namespace: aesthisia-react
spec:
  type: NodePort
  selector:
    app: aesthisia
  ports:
    - name: my-app
      port: 80
      targetPort: 3000
