apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aesthisia-ingress
  namespace: aesthisia
  annotations:
    kubernetes.io/rewrite-target: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: react.aesthisia.in
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aesthisia-svc
                port:
                  number: 80