apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aethisia-ingress
  namespace: aesthisia-react
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: react.aesthisia.in
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aesthisia-react-svc
                port:
                  number: 80